// pub mod img_util;
pub mod color;
// pub mod config;
pub mod img_util;
pub mod read_conf;
pub mod sql;
pub mod tencent_ocr;
pub mod translate;
pub mod tray;
pub mod capture_screen;
pub mod offline_ocr;
